version: "3.4"

services:
  php:
    build:
      context: .
      target: php
    hostname: php
    container_name: php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/
    environment:
      DATABASE_URL: 'mysql://${DB_USER}:${DB_PASSWORD}@database:3306/${DB_NAME}'
    networks:
      - symfony

  nginx:
    build:
      context: .
      target: nginx
    hostname: nginx
    container_name: nginx
    depends_on:
      - php
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d/localhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    networks:
      - symfony

  database:
    image: mysql:8.0
    hostname: database
    container_name: mysql
    volumes:
      - symfony-test-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - target: 3306
        published: 3306
    networks:
      - symfony


volumes:
  symfony-test-mysql:
    driver: local

networks:
  symfony:
    driver: bridge